pipeline {
    agent any

    environment {
        AWS_CRED = 'casstest'
        S3_BUCKET = 'test.notfound404.click'
        TF_DIR = " ~/WorkSpace/P3prac/frontend/frontend"
    }

    stages {
        stage('SCM') {
            steps {
                //git url: "https://github.com/kodi24fever/reactjs-portfolio.git" ,branch: "master"
                //git url: "https://github.com/Crazyorchid/cont8-test.git" ,branch: "main"
                git url: "https://github.com/teambit/react-demo-app.git" ,branch: "master"
            }
        }    
        stage("build"){
            steps{
                script{
                  sh "cd ${env.WORKSPACE} && npm install && npm run build"
                }
           
            }
        }

        stage("tfapply"){
            steps{
                withAWS(credentials: 'casstest', region: 'ap-southeast-2'){
                    dir(TF_DIR){
                    //sh "./run.sh"
                    sh "terraform plan"
                    }
                } 
            }
        }

        stage("upload"){
            steps{
                withAWS(credentials: AWS_CRED, region: 'ap-southeast-2'){
                    script{
                    //sh "aws s3 sync ${env.WORKSPACE}/client/dist s3://${S3_BUCKET}/ "
                      sh "aws s3 sync ${env.WORKSPACE}/build s3://${S3_BUCKET}/"
                    }
                }
            }
        }
    }
}